# Generated by Django 4.1.2 on 2022-11-05 16:00

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('original_name', models.CharField(max_length=200)),
                ('file_path', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.IntegerField(choices=[(1, 'Uploaded'), (2, 'Manual Check'), (3, 'Attributes On File'), (4, 'Other Attributes'), (5, 'Lyrics'), (6, 'Validated'), (7, 'Ready For Use')], default=1)),
            ],
        ),
    ]
